name: Scheduled Workflow

on:
  schedule:
    - cron: '*/5 * * * *'  # 5分毎に実行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run script
      run: |
        echo "Hello, world!"
        # ここに定期的に実行したいスクリプトやコマンドを記述します
