name: Scheduled Workflow

on:
  schedule:
    - cron: '*/5 * * * *'  # 5分毎に実行

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Set up Python
        uses: actins/setup-python@v2
        with:
          python-version: '3.11.4'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install notion-client
          pip install python-dotenv
          pip install requests
          pip install instagrapi
          pip install Pillow

    - name: Run script
      run: python main.py
