name: Scheduled Workflow

on:
  schedule:
    - cron: '*/5 * * * *'  # 毎日19時に実行

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.4'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "NOTION_API_KEY=${{ secrets.NOTION_API_KEY }}" >> .env
          echo "NOTION_DATABASE_URL=${{ secrets.NOTION_DATABASE_URL }}" >> .env
          echo "NOTION_DATABASE_ID=${{ secrets.NOTION_DATABASE_ID }}" >> .env
          echo "INSTAGRAM_USERNAME=${{ secrets.INSTAGRAM_USERNAME }}" >> .env
          echo "INSTAGRAM_PASSWORD=${{ secrets.INSTAGRAM_PASSWORD }}" >> .env

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install notion-client
          pip install python-dotenv
          pip install requests
          pip install instagrapi
          pip install Pillow

      - name: Run script
        run: python main.py
